# .github/workflows/commit_now.yml
name: Commit Now Manual
permissions:
  contents: write   # ‚Üê penting
on:
  workflow_dispatch:
    inputs:
      limit:
        description: 'Jumlah commit yang ingin dibuat'
        required: true
        default: '40'
      commit_message:
        description: 'Pesan commit'
        required: true
        default: 'feat: add greening activity'

jobs:
  manual_commit_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate and Commit Changes
        run: |
          git config --local user.email "nerdnomerch@gmail.com"
          git config --local user.name "nerdnomerch"

          limit='${{ github.event.inputs.limit }}'
          echo "Akan membuat ${limit} commit..."

          for (( i=1; i<=limit; i++ )); do
            echo "Manual commit ke-$i pada $(date +'%F %T') $RANDOM" > LAST_UPDATED_MANUAL
            git add LAST_UPDATED_MANUAL
            git commit -m "${{ github.event.inputs.commit_message }} (#$i)"
          done

      - name: Push
        run: git push origin HEAD:main
