# .github/workflows/commit_cheat.yml
name: Auto Commit Scheduled
permissions:
  contents: write   # â† penting
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Modify LAST_UPDATED file
        run: echo "Last scheduled update on $(date)" > LAST_UPDATED

      - name: Commit
        run: |
          git config --local user.email "nerdnomerch@gmail.com"
          git config --local user.name "nerdnomerch"
          git add LAST_UPDATED
          if ! git diff --staged --quiet; then
            git commit -m "chore(bot): auto update activity"
          else
            echo "No changes to commit."
          fi

      - name: Push
        run: git push origin HEAD:main
